app = "fitplot-api"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  FLY = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 6

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "1m0s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"
